### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by snakeeaterbravo** [SumrakDZN/DeathMap#1]
I was able to make the deaths show up but only on a black background. I didn't see how to overlay it over a map. I am an Xbox Nitrado server owner running Livonia and in the config file, I tried both enoch and livonia. Could someone tell me what I'm doing wrong? Thank you.

**Comment by SumrakDZN** [comment]
There is no option like that at the moment. If you are interested in getting an overlay, you will need to use some 3rd app and texture map of Livonia / Chernarus to merge together in a meaningful way.
I can recommend trying out different ways layers can blend in between (blending modes) along playing with the opacity value.

**Comment by snakeeaterbravo** [comment]
Yep, I ended up figuring it out. Thank you so much.
